### PR TITLE
Make pom compliant with OSSHR package guidelines.

### PR DESCRIPTION
**Pull request by tsujamin**
In order to publish on The Central Repository the POM had to be expanded
to include fields required by the OSSHR guidelines
(http://central.sonatype.org/pages/ossrh-guide.html). Support for
publishing from mvn was added and included in the readme.

Currently waiting on OSSHR/Sonatype repository for pushing. Wait till I test deploying a snapshot before merging this.

### CODE REVIEW

**Comment by tsujamin** [comment]
We couldn't use org.rpsl4j as our groupId as we don't own the domain. Changed to com.github.rpsl4j as per OSSHR advisement.

**Comment by tsujamin** [comment]
can deploy snapshot and stage releases, so should be good to go for our upcoming release.
@abn anything missing you can think of?

**Comment by abn** [comment]
@tsujamin apologies; managed to miss this one. The domain ownership is not a requirement to publish it. And we should probably secure it too as i think it is a better option.

**Comment by tsujamin** [comment]
@abn it is to publish through sonatype, but I'll transfer it across soon

**Comment by abn** [comment]
@tsujamin sounds good to me.

**Pull request merged**
